# coding: utf-8

"""
    Smooch

    The Smooch API is a unified interface for powering messaging in your customer experiences across every channel. Our API speeds access to new markets, reduces time to ship, eliminates complexity, and helps you build the best experiences for your customers. For more information, visit our [official documentation](https://docs.smooch.io).

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import smooch
from smooch.rest import ApiException
from smooch.apis.webhook_api import WebhookApi


class TestWebhookApi(unittest.TestCase):
    """ WebhookApi unit test stubs """

    def setUp(self):
        self.api = smooch.apis.webhook_api.WebhookApi()

    def tearDown(self):
        pass

    def test_create_webhook(self):
        """
        Test case for create_webhook

        
        """
        pass

    def test_delete_webhook(self):
        """
        Test case for delete_webhook

        
        """
        pass

    def test_get_webhook(self):
        """
        Test case for get_webhook

        
        """
        pass

    def test_list_webhooks(self):
        """
        Test case for list_webhooks

        
        """
        pass

    def test_update_webhook(self):
        """
        Test case for update_webhook

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
