# coding: utf-8

"""
    Smooch

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InitResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, app_user=None, app=None):
        """
        InitResponse - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'app_user': 'AppUser',
            'app': 'App'
        }

        self.attribute_map = {
            'app_user': 'appUser',
            'app': 'app'
        }

        self._app_user = app_user
        self._app = app

    @property
    def app_user(self):
        """
        Gets the app_user of this InitResponse.

        :return: The app_user of this InitResponse.
        :rtype: AppUser
        """
        return self._app_user

    @app_user.setter
    def app_user(self, app_user):
        """
        Sets the app_user of this InitResponse.

        :param app_user: The app_user of this InitResponse.
        :type: AppUser
        """
        if app_user is None:
            raise ValueError("Invalid value for `app_user`, must not be `None`")

        self._app_user = app_user

    @property
    def app(self):
        """
        Gets the app of this InitResponse.

        :return: The app of this InitResponse.
        :rtype: App
        """
        return self._app

    @app.setter
    def app(self, app):
        """
        Sets the app of this InitResponse.

        :param app: The app of this InitResponse.
        :type: App
        """
        if app is None:
            raise ValueError("Invalid value for `app`, must not be `None`")

        self._app = app

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InitResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
