# coding: utf-8

"""
    Sunshine Conversations API

    The version of the OpenAPI document: 17.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from sunshine_conversations_client.model.conversation_truncated import ConversationTruncated
from sunshine_conversations_client.model.referral import Referral
from sunshine_conversations_client.model.source_with_campaign_webhook import SourceWithCampaignWebhook
from sunshine_conversations_client.model.user import User
from typing import Optional, Set
from typing_extensions import Self

class ConversationReferralEventAllOfPayload(BaseModel):
    """
    The payload of the event. The contents of this object depend on the type of event.
    """ # noqa: E501
    conversation: Optional[ConversationTruncated] = Field(default=None, description="The conversation a user lands in after being referred. See the <a href=\"https://developer.zendesk.com/documentation/conversations/messaging-platform/programmable-conversations/conversation-referrals/\">conversation referrals</a> guide for more details.")
    user: Optional[User] = Field(default=None, description="The user associated with the conversation.")
    source: Optional[SourceWithCampaignWebhook] = Field(default=None, description="The source of the referral.")
    referral: Optional[Referral] = None
    __properties: ClassVar[List[str]] = ["conversation", "user", "source", "referral"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConversationReferralEventAllOfPayload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of conversation
        if self.conversation:
            _dict['conversation'] = self.conversation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict['user'] = self.user.to_dict()
        # override the default output from pydantic by calling `to_dict()` of source
        if self.source:
            _dict['source'] = self.source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of referral
        if self.referral:
            _dict['referral'] = self.referral.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConversationReferralEventAllOfPayload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "conversation": ConversationTruncated.from_dict(obj["conversation"]) if obj.get("conversation") is not None else None,
            "user": User.from_dict(obj["user"]) if obj.get("user") is not None else None,
            "source": SourceWithCampaignWebhook.from_dict(obj["source"]) if obj.get("source") is not None else None,
            "referral": Referral.from_dict(obj["referral"]) if obj.get("referral") is not None else None
        })
        return _obj


