# coding: utf-8

"""
    Sunshine Conversations API

    The version of the OpenAPI document: 17.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


from sunshine_conversations_client.configuration import Configuration
from sunshine_conversations_client.undefined import Undefined


class ConversionEventsBody(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'messenger': 'MetaConversionEvent'
        'instagram': 'MetaConversionEvent'
        'whatsapp': 'MetaConversionEvent'
    }

    attribute_map = {
        'messenger': 'messenger'
        'instagram': 'instagram'
        'whatsapp': 'whatsapp'
    }

    nulls = set()

    def __init__(self, messenger=None, instagram=None, whatsapp=None, local_vars_configuration=None):  # noqa: E501
        """ConversionEventsBody - a model defined in OpenAPI"""  # noqa: E501
        
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._messenger = None
        self._instagram = None
        self._whatsapp = None
        self.discriminator = None

        if messenger is not None:
            self.messenger = messenger
        if instagram is not None:
            self.instagram = instagram
        if whatsapp is not None:
            self.whatsapp = whatsapp

    @property
    def messenger(self):
        """Gets the messenger of this ConversionEventsBody.  # noqa: E501


        :return: The messenger of this ConversionEventsBody.  # noqa: E501
        :rtype: MetaConversionEvent
        """
        return self._messenger

    @messenger.setter
    def messenger(self, messenger):
        """Sets the messenger of this ConversionEventsBody.


        :param messenger: The messenger of this ConversionEventsBody.  # noqa: E501
        :type: MetaConversionEvent
        """

        self._messenger = messenger

    @property
    def instagram(self):
        """Gets the instagram of this ConversionEventsBody.  # noqa: E501


        :return: The instagram of this ConversionEventsBody.  # noqa: E501
        :rtype: MetaConversionEvent
        """
        return self._instagram

    @instagram.setter
    def instagram(self, instagram):
        """Sets the instagram of this ConversionEventsBody.


        :param instagram: The instagram of this ConversionEventsBody.  # noqa: E501
        :type: MetaConversionEvent
        """

        self._instagram = instagram

    @property
    def whatsapp(self):
        """Gets the whatsapp of this ConversionEventsBody.  # noqa: E501


        :return: The whatsapp of this ConversionEventsBody.  # noqa: E501
        :rtype: MetaConversionEvent
        """
        return self._whatsapp

    @whatsapp.setter
    def whatsapp(self, whatsapp):
        """Sets the whatsapp of this ConversionEventsBody.


        :param whatsapp: The whatsapp of this ConversionEventsBody.  # noqa: E501
        :type: MetaConversionEvent
        """

        self._whatsapp = whatsapp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConversionEventsBody):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ConversionEventsBody):
            return True

        return self.to_dict() != other.to_dict()
