# coding: utf-8

"""
    Sunshine Conversations API

    The version of the OpenAPI document: 17.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from sunshine_conversations_client.model.default_responder_default_responder import DefaultResponderDefaultResponder
from sunshine_conversations_client.model.integration import Integration
from sunshine_conversations_client.model.status import Status
from typing import Optional, Set
from typing_extensions import Self

class Messagebird(Integration):
    """
    Messagebird
    """ # noqa: E501
    default_responder_id: Optional[StrictStr] = Field(default=None, description="The default responder ID for the integration. This is the ID of the responder that will be used to send messages to the user. For more information, refer to the <a href=\"https://developer.zendesk.com/documentation/conversations/messaging-platform/programmable-conversations/switchboard/#default-integration-assignment\">Switchboard guide</a>. ", alias="defaultResponderId")
    default_responder: Optional[DefaultResponderDefaultResponder] = Field(default=None, alias="defaultResponder")
    type: Optional[StrictStr] = Field(default='messagebird', description="To configure a MessageBird integration, acquire the accessKey, the signingKey and the MessageBird number you would like to use, then call the Create Integration endpoint. The response will include the integration’s `_id` and `webhookSecret`, which must be used to configure the webhook in MessageBird. In the Flow Builder for the MessageBird number you’ve used to integrate, add a new step with the following settings: - Create a new Call HTTP endpoint with SMS flow. - Select your desired SMS number for Incoming SMS. - Click on Forward to URL and set its method to POST. - Then, using the integration _id and webhookSecret returned from the create integration call, enter the following into the URL field:  `https://app.smooch.io/api/messagebird/webhooks/{appId}/{integrationId}/{webhookSecret}` - Select application/json for the Set Content-Type header field. - Save and publish your changes. ")
    access_key: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(description="The public API key of your MessageBird account.", alias="accessKey")
    signing_key: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(description="The signing key of your MessageBird account. Used to validate the webhooks' origin.", alias="signingKey")
    originator: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Sunshine Conversations will receive all messages sent to this phone number.")
    webhook_secret: Optional[StrictStr] = Field(default=None, description="The secret that is used to configure webhooks in MessageBird.", alias="webhookSecret")
    __properties: ClassVar[List[str]] = ["id", "type", "status", "displayName", "defaultResponderId", "defaultResponder", "accessKey", "signingKey", "originator", "webhookSecret"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Messagebird from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "webhook_secret",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of default_responder
        if self.default_responder:
            _dict['defaultResponder'] = self.default_responder.to_dict()
        # set to None if display_name (nullable) is None
        # and model_fields_set contains the field
        if self.display_name is None and "display_name" in self.model_fields_set:
            _dict['displayName'] = None

        # set to None if default_responder_id (nullable) is None
        # and model_fields_set contains the field
        if self.default_responder_id is None and "default_responder_id" in self.model_fields_set:
            _dict['defaultResponderId'] = None

        # set to None if default_responder (nullable) is None
        # and model_fields_set contains the field
        if self.default_responder is None and "default_responder" in self.model_fields_set:
            _dict['defaultResponder'] = None

        # set to None if access_key (nullable) is None
        # and model_fields_set contains the field
        if self.access_key is None and "access_key" in self.model_fields_set:
            _dict['accessKey'] = None

        # set to None if signing_key (nullable) is None
        # and model_fields_set contains the field
        if self.signing_key is None and "signing_key" in self.model_fields_set:
            _dict['signingKey'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Messagebird from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type") if obj.get("type") is not None else 'messagebird',
            "status": obj.get("status"),
            "displayName": obj.get("displayName"),
            "defaultResponderId": obj.get("defaultResponderId"),
            "defaultResponder": DefaultResponderDefaultResponder.from_dict(obj["defaultResponder"]) if obj.get("defaultResponder") is not None else None,
            "accessKey": obj.get("accessKey"),
            "signingKey": obj.get("signingKey"),
            "originator": obj.get("originator"),
            "webhookSecret": obj.get("webhookSecret")
        })
        return _obj


